# Generated by Django 4.2.16 on 2024-11-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingproducts',
            name='max_limit',
            field=models.IntegerField(null=True),
        ),
    ]
